name: CI-Docker

on:
  push:
    branches:
      - dockertest
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
         java-version: '17'
         distribution: 'temurin'
         cache: maven

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and start Docker Compose services
        run: |
          docker-compose -f docker-compose-hubNode.yml up -d
      - name: Wait for services to start
        run: sleep 10

      - name: Run Maven tests
        run: mvn test

      - name: Stop Docker Compose services
        run: |
          docker-compose -f docker-compose-hubNode.yml down

      - uses: actions/upload-artifact@v4
        with:
         name: SparkReport
         path: ExtentReports/**/Reports/
